"""create health events table

Revision ID: 33ebc4a1edb5
Revises: 6edb43b1b0c1
Create Date: 2026-07-15 16:11:27.497958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33ebc4a1edb5'
down_revision: Union[str, Sequence[str], None] = '6edb43b1b0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('external_event_id', sa.String(length=150), nullable=True),
    sa.Column('metric_type', sa.Enum('HEART_RATE', 'SPO2', 'ACTIVITY', 'INACTIVITY', 'SLEEP', 'BATTERY_LEVEL', 'CONNECTION_STATUS', 'SYNC_STATUS', name='metric_type'), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('text_value', sa.String(length=100), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('metric_unit', sa.String(length=30), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_status', sa.Enum('VALID_REALTIME', 'DELAYED_USABLE', 'INVALID', name='validation_status'), nullable=False),
    sa.Column('validation_reason', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['elderly_patients.patient_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('external_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("health_events")

    sa.Enum(name="validation_status").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="metric_type").drop(
        op.get_bind(),
        checkfirst=True,
    )