"""create elderly patients table

Revision ID: 6edb43b1b0c1
Revises: f71943451056
Create Date: 2026-07-15 16:06:43.955357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6edb43b1b0c1"
down_revision: Union[str, Sequence[str], None] = "f71943451056"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "elderly_patients",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column("birthdate", sa.Date(), nullable=False),
        sa.Column(
            "sex",
            sa.Enum("MALE", "FEMALE", "OTHER", name="patient_sex"),
            nullable=False,
        ),
        sa.Column("known_conditions", sa.Text(), nullable=True),
        sa.Column("medications", sa.Text(), nullable=True),
        sa.Column("doctor_info", sa.Text(), nullable=True),
        sa.Column("health_notes", sa.Text(), nullable=True),
        sa.Column("normal_hr_min", sa.SmallInteger(), nullable=True),
        sa.Column("normal_hr_max", sa.SmallInteger(), nullable=True),
        sa.Column("usual_spo2_min", sa.SmallInteger(), nullable=True),
        sa.Column("usual_spo2_max", sa.SmallInteger(), nullable=True),
        sa.Column(
            "health_platform",
            sa.Enum(
                "HEALTH_CONNECT", "SIMULATOR", "MANUAL_TEST", name="health_platform"
            ),
            nullable=False,
        ),
        sa.Column("device_brand", sa.String(length=50), nullable=True),
        sa.Column("device_model", sa.String(length=100), nullable=True),
        sa.Column(
            "integration_status",
            sa.Enum(
                "NOT_CONNECTED",
                "CONNECTED",
                "SYNCING",
                "FAILED",
                "DISCONNECTED",
                name="integration_status",
            ),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.household_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("patient_id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("elderly_patients")

    sa.Enum(name="integration_status").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="health_platform").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="patient_sex").drop(
        op.get_bind(),
        checkfirst=True,
    )
