"""create event evaluations table

Revision ID: 727832af6d64
Revises: 33ebc4a1edb5
Create Date: 2026-07-15 18:41:31.770792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727832af6d64'
down_revision: Union[str, Sequence[str], None] = '33ebc4a1edb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_evaluations',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('condition_key', sa.Enum('HR_HIGH', 'HR_LOW', 'SPO2_LOW', 'INACTIVITY', 'NO_DATA', 'DEVICE_DISCONNECTED', 'BATTERY_LOW', 'SYNC_FAILURE', name='condition_key'), nullable=False),
    sa.Column('threshold_value_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('threshold_met', sa.Boolean(), nullable=False),
    sa.Column('persistence_met', sa.Boolean(), nullable=False),
    sa.Column('previous_state', sa.Enum('STABLE', 'ELEVATED', 'WARNING', 'CRITICAL', 'RESOLVED', 'UNKNOWN', name='monitoring_state'), nullable=False),
    sa.Column('new_state', sa.Enum('STABLE', 'ELEVATED', 'WARNING', 'CRITICAL', 'RESOLVED', 'UNKNOWN', name='monitoring_state'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='evaluation_severity'), nullable=False),
    sa.Column('evaluation_reason', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['health_events.event_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("event_evaluations")

    sa.Enum(name="evaluation_severity").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="monitoring_state").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="condition_key").drop(
        op.get_bind(),
        checkfirst=True,
    )