"""create condition trackers table

Revision ID: 92c3a7fee6de
Revises: 727832af6d64
Create Date: 2026-07-15 19:06:51.963924

"""

from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "92c3a7fee6de"
down_revision: Union[str, Sequence[str], None] = "727832af6d64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "condition_trackers",
        sa.Column("condition_tracker_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("last_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "condition_key",
            postgresql.ENUM(
                "HR_HIGH",
                "HR_LOW",
                "SPO2_LOW",
                "INACTIVITY",
                "NO_DATA",
                "DEVICE_DISCONNECTED",
                "BATTERY_LOW",
                "SYNC_FAILURE",
                name="condition_key",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_event_id"],
            ["health_events.event_id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["elderly_patients.patient_id"],
        ),
        sa.PrimaryKeyConstraint("condition_tracker_id"),
        sa.UniqueConstraint(
            "patient_id",
            "condition_key",
            name="uq_condition_trackers_patient_condition",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("condition_trackers")
    # ### end Alembic commands ###
