"""create households table

Revision ID: f71943451056
Revises: 24d9744c5a36
Create Date: 2026-07-15 16:01:19.144883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71943451056'
down_revision: Union[str, Sequence[str], None] = '24d9744c5a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('household_name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('household_notes', sa.Text(), nullable=True),
    sa.Column('household_status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='household_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('household_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("households")

    sa.Enum(name="household_status").drop(
        op.get_bind(),
        checkfirst=True,
    )